### ISSUE TITLE
Link to license is wrong

### ISSUE THREAD

**Issue by woodii** [k3b/k3b-geoHelper#8]
Your artifacts license currently points to https://github.com/k3b/k3b-geoHelper/blob/main/LICENSE -> HTTP 404

You could directly use Apache 2.0 in your `publish-module.gradle`

```
license {
    name = "The Apache Software License, Version 2.0"
    url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
}
```

**Comment by k3b** [comment]
where do you get the license link from? on the project-s main page at the right menu there is a link  to https://github.com/k3b/k3b-geoHelper/blob/master/LICENSE which is working

**Comment by woodii** [comment]
Oh sorry for the unclear statement. I used a gradle plugin to parse dependencies and include it in my app.
The plugin parses pom files and there the link is broken. It should further directly reference apaches license directly.

https://jitpack.io/com/github/k3b/k3b-geoHelper/k3b-geoHelperAndroid/v1.1.10/k3b-geoHelperAndroid-v1.1.10.pom

**Comment by k3b** [comment]
thanks for info.

fixed in https://jitpack.io/com/github/k3b/k3b-geoHelper/k3b-geoHelperAndroid/v1.1.11/k3b-geoHelperAndroid-v1.1.11.pom
